### ISSUE TITLE
Date in RFC 882 format

### ISSUE THREAD

**Issue by optikfluffel** [BennyHallett/elixir-rss#5]
Shouldn't `elixir-rss` maybe just take a normal Erlang datetime tuple and handle the conversion to the RFC 882 format itself?

**Comment by BennyHallett** [comment]
Yep, it definitely should. I was pretty new to Erlang + Elixir when I started this project and I haven't updated it in ages despite it not producing valid XML yet. This is one of the main issues with it though, definitely something I'd like to fix.

Thanks for reporting it!

**Comment by optikfluffel** [comment]
I've checked a generated feed using https://validator.w3.org/feed, the only things I found wrong were that the language should be `en-us` instead of `lang (en-us)` (ISO-639 language code to be precise) and the `guid` should be an url or else there should be a `isPermaLink` property that's set to false, everything else was valid RSS.
