### ISSUE TITLE
Only require title, link and description

### ISSUE THREAD

**Issue by optikfluffel** [BennyHallett/elixir-rss#6]
Since `<pubDate>` and `<guid>` for an `item` [are optional in the specification](https://validator.w3.org/feed/docs/rss2.html#ltpubdategtSubelementOfLtitemgt) we should make them optional in here as well right?
[Same goes](https://validator.w3.org/feed/docs/rss2.html#optionalChannelElements) for `<lastBuildDate>` and `<language>` when creating a `channel`.

**Comment by BennyHallett** [comment]
:+1:
